#!/bin/bash

if [ "$#" -eq 0 ] || [ ! -f "$1" ]; then
    echo "Usage: $0 playbook.yml"
    exit 1
fi

playbook="$1"
shift

master_ip=$(grep -A1 '\[master\]' inventory  | grep -o 'ansible_host=\S\+' | cut -d= -f2)

ansible-playbook \
    -e "ssh_key=../kubenow-infrastructure/ssh_key" \
    -e "master_ip=$master_ip" \
    --key-file ../kubenow-infrastructure/ssh_key \
    "$@" \
    "$playbook"
